# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Artificial Intelligence
tagline:             'AIMA Exercises '
description:         'AIMA Exercises: Exercises for the book Artificial Intelligence: A Modern Approach'
url:                 https://aimacode.github.io/aima-exercises/
baseurl:             '/aima-exercises'
incremental: true


# About/contact
author:
  name:              Sachin Chopra
  url:               sachin10101998.github.io
  email:             schopra@mt.iitr.ac.in

# Custom vars
version:             1.0.0
plugins:
  - jekyll-paginate
paginate: 5
#Staticman 
staticman:
  repository : sachin10101998/aima-exercises # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : "master"  # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>
